# My variables
name: Simone Dassi
description: Blog about 3d printing, raspberry, arduino and coding
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
